### ISSUE TITLE
Make params a dictionary, not array

### ISSUE THREAD

**Issue by enver** [saltstack-formulas/sysctl-formula#9]
Do you think that params should be set as dictionary instead of array? With current implementation it is impossible to override defaults params without redefining all of them. E.g. if i set defaults like this:

```
sysctl:
  lookup:
    pkg: procps
    config:
      location: '/etc/sysctl.conf'
    params:
      - name: net.ipv4.ip_forward
        value: 1
      - name: net.core.somaxconn
        value: 65536
      - name: fs.file-max
        value: 65536
      - name: vm.swappiness
        value: 60
```

and want to override some param, e.g vm.swappiness for certain set of servers I'd need to redefine all params above instead of just redefining vm.swappiness. But if params were set like dictionary:

```
sysctl:
  lookup:
    pkg: procps
    config:
      location: '/etc/sysctl.conf'
    params:
      net.ipv4.ip_forward:
        value: 1
      net.core.somaxconn:
        value: 65536
      fs.file-max:
        value: 65536
        config: fs.conf
      vm.swappiness:
        value: 60
```

overriding vm.swappiness would require following configuration:

```
sysctl:
  lookup:
    params:
      vm.swappiness:
        value: 20
```

Thoughts?
